### ISSUE TITLE
Hi, I use this and have some problems，it can't work

### ISSUE THREAD

**Issue by xiaodeyue2** [Danny-Dasilva/cycletls_python#9]
D:\python\python.exe D:/python/rs/cycletls_python-main/client.py
Traceback (most recent call last):
  File "D:/python/rs/cycletls_python-main/client.py", line 1, in <module>
    from cycletls import CycleTLS
  File "D:\python\rs\cycletls_python-main\cycletls\__init__.py", line 1, in <module>
    from .api import CycleTLS
  File "D:\python\rs\cycletls_python-main\cycletls\api.py", line 3, in <module>
    from .schema import Response, Request
  File "D:\python\rs\cycletls_python-main\cycletls\schema.py", line 9, in <module>
    class Request(BaseModel):
  File "D:\python\rs\cycletls_python-main\cycletls\schema.py", line 19, in Request
    cookies: Optional[list[Cookie]] = None
TypeError: 'type' object is not subscriptable

This is the first problem, I tried to rewrite line 19 of schema.py file, delete [Cookie]
After re-run,
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:\python\rs\cycletls_python-main\cycletls\api.py", line 25, in __init__
    self.ws = create_connection("ws://localhost:8080")
  File "D:\python\lib\site-packages\websocket\_core.py", line 601, in create_connection
    websock.connect(url, **options)
  File "D:\python\lib\site-packages\websocket\_core.py", line 245, in connect
    options.pop('socket', None))
  File "D:\python\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\python\lib\site-packages\websocket\_http.py", line 206, in _open_socket
    raise err
  File "D:\python\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] Unable to connect because the target computer actively refused.

I don't quite understand the contents of the bottom 24th to 33rd line in the api.py file, subprocess.Popen, I guess the error may be because the executed file does not seem to exist.Looking forward to your replies and updates.

**Comment by mminovv** [comment]
@Danny-Dasilva Hi, Great project. I too have encountered this problem. I have a memory leak. I'm building cycletls on Docker with Nodejs and connecting to it via ws. And I don't understand why there is a leak inside the cycletls container. Why is this happening?

**Comment by Azulax90** [comment]
how i can solve this ?

**Comment by morrphology** [comment]
port 8080 is probably in use so could change 
```py
create_connection("ws://localhost:8080")
```
to smth like
```py
create_connection("ws://localhost:8050")
```
